% BactProd_plots.m

% Created by Jamie Collins, james.r.collins@aya.yale.edu, on 11/3/2013
% Revised by J.R.C., 12/1/2015, to make suitable for upload to GitHub

% Purpose: Generates summary statistics and plots from bacterial production
% data from the BLATZ II and NA VICE cruises (KN207-1 and KN207-3). Uses
% as input the BP rates calculated using the script riBPdata.m. This script was used
% to generate the various BP plots presented in Collins, J. R.,
% B. R. Edwards, K. Thamatrakoln, J. E. Ossolinski, G. R. DiTullio, K. D.
% Bidle, S. C. Doney, and B. A. S. Van Mooy. 2015. The multiple fates of
% sinking particles in the North Atlantic Ocean. Global Biogeochem. Cycles
% 29: 1471-1494, doi:10.1002/2014GB005037

% Dependencies:
%
%  1. Requires the function errorbar_tick (by Arnaud Laurent) for 
%  fine-tuning the widths of error bars. The m-file errorbar_tick.m is
%  provided at http://github.com/jamesrco/3H_Leu_BactProd/errorbar_tick.m
%  under the BSD License. The original can be downloaded from the MATLAB
%  file exchange at:
%  http://www.mathworks.com/matlabcentral/fileexchange/22826-adjust-error-bar-width/content/errorbar_tick.m
%
%  2. Requires as input two of the .csv files generated by riBPdata.m:
%  3H_Leu_BactProd_calcs_by_station_no.csv and
%  3H_Leu_BactProd_calcs_replicate_averaged_by_CTD.csv



%% User specify file locations and values of some constants

% first, clean up workspace
clear all; close all;

% define a screen size variable so we can make figures that look decent
scrsz = get(0,'ScreenSize'); 

% define directory containing files generated by riBPdata.m
BPdata_directory = 'sample_data_metadata/';

% specify paths to the two required .csv files
BP_datafile_replicate_averaged_by_CTD = '3H_Leu_BactProd_calcs_replicate_averaged_by_CTD.csv';
BP_datafile_data_by_station = '3H_Leu_BactProd_calcs_by_station_no.csv';

% define values of some constants; note that Collins et al. 2015 evaluates
% sensitivity to changes in the values of these parameters

ID = 1; % isotope dilution; value of 1 will yield most conservative estimate
leu_BPAA = 0.073; % mol fraction leucine : total bacterial amino acids
leu_BPAA_uncert = 0.0191; % associated uncertainty
C_prot = 0.86; % mass ratio cellular carbon : protein for marine bacteria
MW_leu = 131.2; % molecular weight of leucine

% values of leu_BPAA, leu_BPAA_uncert, C_prot from Simon, M., and F. Azam.
% 1989. Protein-content and protein-synthesis rates of planktonic marine
% bacteria. Mar. Ecol. Prog. Ser. 51: 201-213.

%% Load data

% BP data first

BP_replicate_averaged_by_CTD = csvread(strcat(BPdata_directory,BP_datafile_replicate_averaged_by_CTD),1,0);

size = size(BP_replicate_averaged_by_CTD);
numcols = size(2);

fid = fopen(strcat(BPdata_directory,BP_datafile_replicate_averaged_by_CTD));

BP_replicate_averaged_by_CTD_headers = textscan(fid,'%s',numcols,'delimiter',',');

fclose(fid);

% extract data from matrix into separate vectors and then assign vector
% names

for i=1:numcols
    colname = BP_replicate_averaged_by_CTD_headers{1,1}(i);
    colname = char(colname);
    colnumber = num2str(i);
    commandExec = strcat(colname,'=','BP_replicate_averaged_by_CTD(:,',colnumber,');');
    evalin('base', commandExec );
end

clear i

% separate data by cruise, then extract data into separate vectors and assign vector
% names 

cruises=unique(Cruise_ID);

for i=1:length(cruises)
    thiscruise=cruises(i);
    cruise_ind=find(BP_replicate_averaged_by_CTD(:,1)==thiscruise);
    subsetname=strcat('BP_replicate_averaged_by_CTD_',num2str(thiscruise));
    for j=1:length(cruise_ind)
        thisrecord=cruise_ind(j);
        commandExec = strcat(subsetname,'(',num2str(j),',',...
            ':)=','BP_replicate_averaged_by_CTD(',num2str(cruise_ind(j)),',:);');
        evalin('base', commandExec );
    end
end

clear i j

% extract data from cruise-specific matrices into separate vectors and then assign vector
% names

for i=1:length(cruises)
    thiscruise=cruises(i);
    cruise_ind=find(BP_replicate_averaged_by_CTD(:,1)==thiscruise);
    subsetname=strcat('BP_replicate_averaged_by_CTD_',num2str(thiscruise));
    for j=1:numcols
        colname = BP_replicate_averaged_by_CTD_headers{1,1}(j);
        colname = char(colname);
        colnumber = num2str(j);
        commandExec = strcat(colname,'_',num2str(thiscruise),'=',subsetname,'(:,',colnumber,');');
        evalin('base', commandExec );
    end
end

clear i j

% now, station data

Station_data_by_station_no = csvread(strcat(BPdata_directory,BP_datafile_data_by_station),1,0);

numcols = 13;

fid = fopen(strcat(BPdata_directory,BP_datafile_data_by_station));

Station_data_by_station_no_headers = textscan(fid,'%s',numcols,'delimiter',',');

fclose(fid);

% extract data from matrix into separate vectors and then assign vector
% names

for i=1:numcols
    colname = Station_data_by_station_no_headers{1,1}(i);
    colname = char(colname);
    colnumber = num2str(i);
    commandExec = strcat('Station_data_',colname,'=','Station_data_by_station_no(:,',colnumber,');');
    evalin('base', commandExec );
end

clear i


%% Analyze signal:noise by depth

depths=unique(Depth);

signoise_data=nan(100,length(depths));

for i=1:length(depths)
    thisdepth=depths(i);
    depth_ind=find(Depth==thisdepth);
    signoise_data_thisdepth = Signal_to_noise_ratio(depth_ind);
    signoise_data(1:length(signoise_data_thisdepth),i)=signoise_data_thisdepth;
end

% have to get rid of one major outlier

signoise_data(signoise_data>100)=NaN;

nan_ind = find(isnan(signoise_data));
signoise_data_no_blanks = signoise_data;
signoise_data_no_blanks(nan_ind)=[];
signoise_mean = mean(signoise_data_no_blanks(:));

%% Plots of some statistical information

subplot(2,2,[1,2]); % uptake rates, all data
boxplot(Trit_leu_uptake_pmol_L_hr,Depth);
xlabel('Depth (m)','FontSize',14);
ylabel(['BP (pmol leu L-1 hr-1)'],'FontSize',14);
xticklabels=[2 8 13 18 24 29 34 40 50 60 70 95 200];
set(gca,'XTick',1:5:depths(length(depths)),'XTickLabel',xticklabels);
title(['Bacterial production rates in the North Atlantic Ocean' char(10)...
    'KN207-1 and KN207-3, all data'],'FontSize',16);

subplot(2,2,3); % live samples and kills, all data
h = errorbar(Depth,Mean_trit_leu_uptake_live_samples_pmol_L_hr,...
    Std_dev_trit_leu_uptake_live_samples_pmol_L_hr,'.','LineWidth',1);
% errorbar_tick(h,140);
axis([0 200 0 45]);
xlabel('Depth (m)','FontSize',14);
ylabel(['BP (pmol leu L-1 hr-1)'],'FontSize',14);
hold on
plot(Depth,Trit_leu_uptake_killed_control_pmol_L_hr,'r.');
% set(gca,'XTick',1:5:depths(length(depths)),'XTickLabel',xticklabels);
hleg = legend(['Live samples (mean value; error' char(10) 'bars are standard deviation)'],'Killed control');
set(hleg,'FontSize',9,'box','on');
title(['Live samples vs. killed controls'],'FontSize',14);
hold off;

subplot(2,2,4); % signal to noise
boxplot(signoise_data,depths);
text(58,17,'* mean uptake rate measured in live samples:rate measured in killed control',...
    'HorizontalAlignment','right','FontSize',8);
xlabel('Depth (m)','FontSize',14);
ylabel(['"Signal to noise" ratio*'],'FontSize',14);
xticklabels=[2 8 13 18 24 29 34 40 50 60 70 95 200];
axis([0 62 0 18]);
set(gca,'XTick',1:5:depths(length(depths)),'XTickLabel',xticklabels);
hold on;
plot([0 200],[signoise_mean signoise_mean],'r--');
title(['"Signal to noise" ratio in KN207-1 and KN207-3 bacterial production data'],'FontSize',14);
hold off;

%% convert BP rates to units of C

BP_mmol_C_m3_d_2073 = Trit_leu_uptake_pmol_L_hr_2073*24*1000*(1/10^9).*MW_leu*(1/leu_BPAA)*C_prot*(1/12.01)*ID;
BP_mmol_C_m3_d_2071 = Trit_leu_uptake_pmol_L_hr_2071*24*1000*(1/10^9).*MW_leu*(1/leu_BPAA)*C_prot*(1/12.01)*ID;

BP_mg_C_m3_d_2073 = BP_mmol_C_m3_d_2073*12.01;
BP_mg_C_m3_d_2071 = BP_mmol_C_m3_d_2071*12.01;

BP_mmol_C_m3_d_2073_uncert = Std_dev_trit_leu_uptake_pmol_L_hr_2073*24*1000*(1/10^9).*MW_leu*(1/leu_BPAA)*C_prot*(1/12.01)*ID;
BP_mmol_C_m3_d_2071_uncert = Std_dev_trit_leu_uptake_pmol_L_hr_2071*24*1000*(1/10^9).*MW_leu*(1/leu_BPAA)*C_prot*(1/12.01)*ID;

BP_mg_C_m3_d_2073_uncert = BP_mmol_C_m3_d_2073_uncert*12.01;
BP_mg_C_m3_d_2071_uncert = BP_mmol_C_m3_d_2071_uncert*12.01;

%% Along-track plot for cruise KN207-3, in mg C/m3/d

figure('Position',[1 scrsz(4)*1/4 scrsz(3)*(10/10) scrsz(4)*4/10])
set(gcf,'PaperPositionMode','auto')

% in mg C/m3/d

% histogram of uptake rates

subplot(2,10,[9:10]);
hist(BP_mg_C_m3_d_2073,30);
xlabel('BP (mg C m-3 d-1)');
ylabel('No. observations');

% contour plot against latitude along cruise track, in mg C m3/d

% first, must interpolate using scatteredInterpolant since data is 
% irregularly spaced; using strictly linear interpolation with contours that connect
% through all data points

ind_exclude=find(isnan(BP_mg_C_m3_d_2073));
BP_mg_C_m3_d_2073_reduced=BP_mg_C_m3_d_2073;
BP_mg_C_m3_d_2073_reduced(ind_exclude)=[];
CTD_station_lat_2073_reduced=CTD_station_lat_2073;
CTD_station_lat_2073_reduced(ind_exclude)=[];
Depth_2073_reduced=Depth_2073;
Depth_2073_reduced(ind_exclude)=[];

F = scatteredInterpolant(CTD_station_lat_2073_reduced,Depth_2073_reduced,...
    BP_mg_C_m3_d_2073_reduced,'natural','linear');

% now, specify some query points and create a grid of data using the
% interpolant

[Xq,Yq] = meshgrid(0:.125:150);

Vq=F(Xq,Yq);

crange=[-0.02 1.8];
numsteps=[-0.02:.025:1.8];
contours=[0 0.5 1.0 1.5 1.8];

subplot(2,10,[1,2,3,4,5,6,7,11,12,13,14,15,16,17])
[c1,h1]=contourf(Xq,-Yq,Vq,numsteps);
set(h1,'edgecolor','none'); % turns off contour lines
hold on
shading flat;
hold on
% [c2,h2]=contour(Xq,-Yq,Vq,contours,'k:');
% clabel(c,h);
% caxis(crange);
xlabel('Degrees north latitude','FontSize',14);
ylabel(['Depth (m)'],'FontSize',14);
axis([CTD_station_lat_2073(1) CTD_station_lat_2073(length(CTD_station_lat_2073))...
    -150 -5]);

h3 = colorbar;
ylabel(h3, 'Bacterial production (mg C m^{-3} d^{-1})')

% overlay CTD data points and color according to whether they've been
% analyzed or not

h4 = plot(CTD_station_lat_2073_reduced,-Depth_2073_reduced,'k+','MarkerSize',5);
h5 = plot(CTD_station_lat_2073(ind_exclude),-Depth_2073(ind_exclude),'ko','MarkerSize',5);
h6 = legend([h4 h5],{'analyzed','no data yet'},'Location','SouthEast','FontSize',12);
set(h6,'FontSize',12,'box','on');
title('Bacterial production along cruise track KN207-3','FontSize',16);
hold off
hold off

%% Along-track plot for cruise KN207-3, in pmol leu/L/hr

figure('Position',[1 scrsz(4)*1/4 scrsz(3)*(10/10) scrsz(4)*4/10])
set(gcf,'PaperPositionMode','auto')

% in pmol leu/L/hr

% histogram of uptake rates

subplot(2,10,[9:10]);
hist(Trit_leu_uptake_pmol_L_hr_2073,30);
xlabel('BP (pmol leu L-1 h-1)');
ylabel('No. observations');

% contour plot against latitude along cruise track, in pmol leu/L/hr

% first, must interpolate using scatteredInterpolant since data is 
% irregularly spaced; using strictly linear interpolation with contours that connect
% through all data points

ind_exclude=find(isnan(Trit_leu_uptake_pmol_L_hr_2073));
Trit_leu_uptake_pmol_L_hr_2073_reduced=Trit_leu_uptake_pmol_L_hr_2073;
Trit_leu_uptake_pmol_L_hr_2073_reduced(ind_exclude)=[];
CTD_station_lat_2073_reduced=CTD_station_lat_2073;
CTD_station_lat_2073_reduced(ind_exclude)=[];
Depth_2073_reduced=Depth_2073;
Depth_2073_reduced(ind_exclude)=[];

F = scatteredInterpolant(CTD_station_lat_2073_reduced,Depth_2073_reduced,...
    Trit_leu_uptake_pmol_L_hr_2073_reduced,'natural','linear');

% now, specify some query points and create a grid of data using the
% interpolant

[Xq,Yq] = meshgrid(0:.125:150);

Vq=F(Xq,Yq);

crange=[-0.02 1.8]./24/1000/(1/10^9)./MW_leu/(1/leu_BPAA)/C_prot/ID;
numsteps=[-0.02:.025:1.8]./24/1000/(1/10^9)./MW_leu/(1/leu_BPAA)/C_prot/ID;
contours=[0 0.5 1.0 1.5 1.8]./24/1000/(1/10^9)./MW_leu/(1/leu_BPAA)/C_prot/ID;

subplot(2,10,[1,2,3,4,5,6,7,11,12,13,14,15,16,17])
[c1,h1]=contourf(Xq,-Yq,Vq,numsteps);
set(h1,'edgecolor','none'); % turns off contour lines
hold on
shading flat;
hold on
% [c2,h2]=contour(Xq,-Yq,Vq,contours,'k:');
% clabel(c,h);
% caxis(crange);
xlabel('Degrees north latitude','FontSize',14);
ylabel(['Depth (m)'],'FontSize',14);
axis([CTD_station_lat_2073(1) 62 -150 -5]);

h3 = colorbar;
ylabel(h3, 'Bacterial production (pmol leu L^{-1} h^{-1})')

% overlay CTD data points and color according to whether they've been
% analyzed or not

h4 = plot(CTD_station_lat_2073_reduced,-Depth_2073_reduced,'k+','MarkerSize',5);
h5 = plot(CTD_station_lat_2073(ind_exclude),-Depth_2073(ind_exclude),'ko','MarkerSize',5);
h6 = legend([h4 h5],{'analyzed','no data yet'},'Location','SouthEast','FontSize',12);
set(h6,'FontSize',12,'box','on');
title('Bacterial production along cruise track KN207-3','FontSize',16);
hold off
hold off

%% Along-track plot for cruise KN207-1, in mg C/m3/d

figure('Position',[1 scrsz(4)*1/4 scrsz(3)*(10/10) scrsz(4)*4/10])
set(gcf,'PaperPositionMode','auto')

% in mg C/m3/d

% histogram of uptake rates

subplot(2,10,[9:10]);
hist(BP_mg_C_m3_d_2071,30);
xlabel('BP (mg C m-3 d-1)');
ylabel('No. observations');

% contour plot against latitude along cruise track

% first, must interpolate using scatteredInterpolant since data is 
% irregularly spaced; using strictly linear interpolation with contours that connect
% through all data points

ind_exclude=find(isnan(BP_mg_C_m3_d_2071));
BP_mg_C_m3_d_2071_reduced=BP_mg_C_m3_d_2071;
BP_mg_C_m3_d_2071_reduced(ind_exclude)=[];
CTD_station_lat_2071_reduced=CTD_station_lat_2071;
CTD_station_lat_2071_reduced(ind_exclude)=[];
Depth_2071_reduced=Depth_2071;
Depth_2071_reduced(ind_exclude)=[];

F = scatteredInterpolant(CTD_station_lat_2071_reduced,Depth_2071_reduced,...
    BP_mg_C_m3_d_2071_reduced,'natural','linear');

% now, specify some query points and create a grid of data using the
% interpolant

[Xq,Yq] = meshgrid(0:.125:150);

Vq=F(Xq,Yq);

crange=[-0.02 1.8];
numsteps=[-0.02:.025:1.8];
contours=[0 0.5 1.0 1.5 1.8];

subplot(2,10,[1,2,3,4,5,6,7,11,12,13,14,15,16,17])
[c1,h1]=contourf(Xq,-Yq,Vq,numsteps);
set(h1,'edgecolor','none'); % turns off contour lines
hold on
shading flat;
hold on
% [c2,h2]=contour(Xq,-Yq,Vq,contours,'k:');
% clabel(c,h);
% caxis(crange);
xlabel('Degrees north latitude','FontSize',14);
ylabel(['Depth (m)'],'FontSize',14);
axis([CTD_station_lat_2071(length(CTD_station_lat_2071)) CTD_station_lat_2071(1)...
    -150 -5]);

h3 = colorbar;
ylabel(h3, 'Bacterial production (mg C m^{-3} d^{-1})')

% overlay CTD data points and color according to whether they've been
% analyzed or not

h4 = plot(CTD_station_lat_2071_reduced,-Depth_2071_reduced,'k+','MarkerSize',5);
h5 = plot(CTD_station_lat_2071(ind_exclude),-Depth_2071(ind_exclude),'ko','MarkerSize',5);
h6 = legend([h4 h5],{'analyzed','no data yet'},'Location','SouthEast','FontSize',12);
set(h6,'FontSize',12,'box','on');
title('Bacterial production along cruise track KN207-1','FontSize',16);
hold off
hold off

%% Along-track plot for cruise KN207-1, in pmol leu/L/hr

figure('Position',[1 scrsz(4)*1/4 scrsz(3)*(10/10) scrsz(4)*4/10])
set(gcf,'PaperPositionMode','auto')

% in pmol leu/L/hr

% histogram of uptake rates

subplot(2,10,[9:10]);
hist(Trit_leu_uptake_pmol_L_hr_2071,30);
xlabel('BP (pmol leu L-1 h-1)');
ylabel('No. observations');

% contour plot against latitude along cruise track

% first, must interpolate using scatteredInterpolant since data is 
% irregularly spaced; using strictly linear interpolation with contours that connect
% through all data points

ind_exclude=find(isnan(Trit_leu_uptake_pmol_L_hr_2071));
Trit_leu_uptake_pmol_L_hr_2071_reduced=Trit_leu_uptake_pmol_L_hr_2071;
Trit_leu_uptake_pmol_L_hr_2071_reduced(ind_exclude)=[];
CTD_station_lat_2071_reduced=CTD_station_lat_2071;
CTD_station_lat_2071_reduced(ind_exclude)=[];
Depth_2071_reduced=Depth_2071;
Depth_2071_reduced(ind_exclude)=[];

F = scatteredInterpolant(CTD_station_lat_2071_reduced,Depth_2071_reduced,...
    Trit_leu_uptake_pmol_L_hr_2071_reduced,'natural','linear');

% now, specify some query points and create a grid of data using the
% interpolant

[Xq,Yq] = meshgrid(0:.125:150);

Vq=F(Xq,Yq);

crange=[-0.02 1.8]./24/1000/(1/10^9)./MW_leu/(1/leu_BPAA)/C_prot/ID;
numsteps=[-0.02:.025:1.8]./24/1000/(1/10^9)./MW_leu/(1/leu_BPAA)/C_prot/ID;
contours=[0 0.5 1.0 1.5 1.8]./24/1000/(1/10^9)./MW_leu/(1/leu_BPAA)/C_prot/ID;

subplot(2,10,[1,2,3,4,5,6,7,11,12,13,14,15,16,17])
[c1,h1]=contourf(Xq,-Yq,Vq,numsteps);
set(h1,'edgecolor','none'); % turns off contour lines
hold on
shading flat;
hold on
% [c2,h2]=contour(Xq,-Yq,Vq,contours,'k:');
% clabel(c,h);
% caxis(crange);
xlabel('Degrees north latitude','FontSize',14);
ylabel(['Depth (m)'],'FontSize',14);
axis([CTD_station_lat_2071(length(CTD_station_lat_2071)) CTD_station_lat_2071(1)...
    -150 -5]);

h3 = colorbar;
ylabel(h3, 'Bacterial production (pmol leu L^{-1} h^{-1})')

% overlay CTD data points and color according to whether they've been
% analyzed or not

h4 = plot(CTD_station_lat_2071_reduced,-Depth_2071_reduced,'k+','MarkerSize',5);
h5 = plot(CTD_station_lat_2071(ind_exclude),-Depth_2071(ind_exclude),'ko','MarkerSize',5);
h6 = legend([h4 h5],{'analyzed','no data yet'},'Location','SouthEast','FontSize',12);
set(h6,'FontSize',12,'box','on');
title('Bacterial production along cruise track KN207-1','FontSize',16);
hold off
hold off
